### ISSUE TITLE
how to use it based on tx1

### ISSUE THREAD

**Issue by Gotta-C** [hexiangquan/tensorRTyoloV3#2]
I have trained yolov3 and transplanted model into tx1,so how to use your code.Which version of tensorRT you used?

**Comment by hexiangquan** [comment]
i will release  caffe support yolov3 you can use it and then install  jetson pack with tensorrt on tx1 board  then  compile

**Comment by Gotta-C** [comment]
My tx1 board was designed not official ,can't support jetson pack.Can I use tensorrt to transform model in server and compiled tensorrt package in tx1 and use the model? And  I have a another problem ,the same model test images in server and tx1 got different result , SSD model doesn't have this problem,i think my board is ok , and i do not know whether it is the darknet to tx1 problem,so can't wait to try your yolov3-caffe
